sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t linuxchain:monero .
  - docker run -d -p 127.0.0.1:80:4567 linuxchain:monero /bin/sh -c "ls -la /wallet"
  - docker ps -a

script:
  - ps auxwww
